name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: release
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-msi:
    name: Build Windows MSI and upload to release
    runs-on: ubuntu-latest
    needs: [release]
    env:
      INSTALLER: .github/win-msi
      BIN: .github/win-msi/src/bin
      WIXIMG: dactiv/wix@sha256:17d232708589641f5632f9a1ff9463ad087b192cea7b8e6012d2b47ec6af5f6c
    steps:
    - name: Strip v from version tag
      run: |
        VER=${{ github.ref }}
        VERSION=${VER//v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "ASSET=saml2aws_${VERSION}_windows_amd64.zip" >> $GITHUB_ENV

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Check out code
      uses: actions/checkout@v2

    - name: Retrieve the release asset
      id: asset
      uses: robinraju/release-downloader@4bdb8ee081c9ee08a35320794dd461312ac9e4ad  # v1.3
      with:
        tag: ${{ github.ref }}
        fileName: ${{ env.ASSET }}
        out-file-path: ${{ env.BIN }}

    - name: Unzip asset
      working-directory: ${{ env.BIN }}
      run: unzip "${ASSET}"

    - name: Build MSI
      run: |
        # container does not run as root
        chmod -R o+rw "${INSTALLER}"

        cat "${INSTALLER}/wix.sh" | docker run --rm -i -e VERSION -v "${INSTALLER}:/wix" ${WIXIMG} /bin/sh

    - name: Upload the asset to the release
      uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5  # v0.1.14 / v1
      with:
        files: ${{ env.INSTALLER }}/out/*.msi
