name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: The tag to run against. This trigger only runs the MSI builder.
        required: true

jobs:
  release:
    name: release
    runs-on: macos-latest
    if: github.event_name != 'workflow_dispatch'
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windows-msi:
    name: Build Windows MSI and upload to release
    runs-on: ubuntu-latest
    needs: [release]
    if: >-  # https://github.com/actions/runner/issues/491
      always() &&
      (needs.release.result == 'success' || needs.release.result == 'skipped')
    env:
      INSTALLER: ${{ github.workspace }}/.github/win-msi
      BIN: ${{ github.workspace }}/.github/win-msi/src/bin
      WIXIMG: dactiv/wix@sha256:17d232708589641f5632f9a1ff9463ad087b192cea7b8e6012d2b47ec6af5f6c
    steps:
    - name: Normalize tag values
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]] ; then
            VER=${{ github.event.inputs.tag }}
        else
            VER=${GITHUB_REF/refs\/tags\//}
        fi

        VERSION=${VER//v}

        echo "VER_TAG=$VER" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "ASSET=saml2aws_${VERSION}_windows_amd64.zip" >> $GITHUB_ENV

    - name: Check out code
      uses: actions/checkout@v2

    - name: Retrieve the release asset
      id: asset
      uses: robinraju/release-downloader@4bdb8ee081c9ee08a35320794dd461312ac9e4ad  # v1.3
      with:
        repository: ${{ github.repository }}
        tag: ${{ env.VER_TAG }}
        fileName: ${{ env.ASSET }}
        out-file-path: ${{ env.BIN }}

    - name: Unzip asset
      working-directory: ${{ env.BIN }}
      run: unzip "${ASSET}"

    - name: Build MSI
      run: |
        # container does not run as root
        chmod -R o+rw "${INSTALLER}"

        cat "${INSTALLER}/wix.sh" | docker run --rm -i -e VERSION -v "${INSTALLER}:/wix" ${WIXIMG} /bin/sh

    - name: Upload the asset to the release
      uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5  # v0.1.14 / v1
      with:
        tag_name: ${{ env.VER_TAG }}
        files: ${{ env.INSTALLER }}/out/*.msi
